### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by TracyZhao24** [dailybruin/prime-execorder9066#3]
- [x] landing image component: full screen landing page with an image (props.landing_image)
- [x] quote with horizontal line after landing image: props.quote_1
- [x] image side-by-side with quote: props.image_with_quote, props.quote_2
- [x] large bold word with text below it and background image behind it: props.emphasis_word, props.emphasis_subtext, props.backround_image
- [ ] main article: prop.article_title, props.article_byline, props.article_date, props.type (options are text, pull, image, header), props
- [ ] pictures in main article: props.value.url, props.value.caption, props.value.credit
- [ ] captions and credits for all images
